### ISSUE TITLE
Some

### ISSUE THREAD

**Issue by lucasfth** [lucasfth/aldes#3]

**Comment by lucasfth** [comment]
Will try to implement it as a normal DFS (of course modified)

**Comment by lucasfth** [comment]
ISSUE.
<img width="291" alt="image" src="https://github.com/user-attachments/assets/eb8203b7-b910-4900-88be-91cf92183f97">
Wrong print when directed graph

**Comment by A-Guldborg** [comment]
@lucasfth what print do you want?
